# Generated by Django 3.2.4 on 2021-06-30 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_service', models.CharField(max_length=13, verbose_name='Номер телефону')),
                ('name_service', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('choice_service', models.CharField(blank=True, max_length=200, null=True, verbose_name='Замовлення послуги')),
                ('text_service', models.TextField(blank=True, null=True, verbose_name='Побажання')),
                ('time_service', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час створення')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=13, verbose_name='Номер телефону')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('text_questions', models.TextField(verbose_name='Текст питання')),
                ('time_question', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час створення')),
            ],
            options={
                'verbose_name': 'Питання',
                'verbose_name_plural': 'Питання',
            },
        ),
        migrations.CreateModel(
            name='ServicesAndPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100, verbose_name='Послуга')),
                ('serviceUA', models.CharField(blank=True, max_length=100, null=True, verbose_name='Послуга UA')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('descriptionUA', models.TextField(blank=True, null=True, verbose_name='Опис UA')),
                ('price', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Ціна')),
                ('si', models.CharField(blank=True, default='грн', max_length=20, null=True, verbose_name='Одиниці виміру')),
                ('siUA', models.CharField(blank=True, default='грн', max_length=20, null=True, verbose_name='Одиниці виміру UA')),
                ('image', models.ImageField(blank=True, null=True, upload_to='var/www/file_project/media/images/', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
            },
        ),
    ]
