# Generated by Django 3.2 on 2021-06-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_servicesandprice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesandprice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/main/img', verbose_name='Изображение'),
        ),
    ]
