# Generated by Django 3.2 on 2021-06-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_servicesandprice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservices',
            name='text_service',
            field=models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3')], max_length=200, verbose_name='Замовлення послуги'),
        ),
        migrations.AlterField(
            model_name='servicesandprice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='var/www/file_project/media/images/', verbose_name='Изображение'),
        ),
    ]
