# Generated by Django 3.2 on 2021-06-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210615_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservices',
            name='text_service',
            field=models.CharField(max_length=200, verbose_name='Замовлення послуги'),
        ),
    ]
