# Generated by Django 3.2 on 2021-06-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_orderservices_text_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservices',
            name='choice_service',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Замовлення послуги'),
        ),
        migrations.AlterField(
            model_name='orderservices',
            name='name_service',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='orderservices',
            name='tel_service',
            field=models.CharField(max_length=13, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='orderservices',
            name='text_service',
            field=models.TextField(blank=True, null=True, verbose_name='Побажання'),
        ),
    ]
