# Generated by Django 3.2 on 2021-06-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210616_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservices',
            name='choice_service',
            field=models.CharField(blank=True, choices=[], max_length=200, null=True, verbose_name='Замовлення послуги'),
        ),
    ]
