# Generated by Django 3.2 on 2021-06-18 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_orderservices_choice_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservices',
            name='time_service',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='questions',
            name='time_question',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
