# Generated by Django 3.2 on 2021-06-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210618_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservices',
            name='time_service',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
