# Generated by Django 3.2.4 on 2021-06-27 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_orderservices_time_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderservices',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Питання', 'verbose_name_plural': 'Питання'},
        ),
        migrations.AlterModelOptions(
            name='servicesandprice',
            options={'verbose_name': 'Послуга', 'verbose_name_plural': 'Послуги'},
        ),
        migrations.AlterField(
            model_name='orderservices',
            name='time_service',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час створення'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='questions',
            name='tel',
            field=models.CharField(max_length=13, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='text_questions',
            field=models.TextField(verbose_name='Текст питання'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='time_question',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час створення'),
        ),
        migrations.AlterField(
            model_name='servicesandprice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='servicesandprice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='var/www/file_project/media/images/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='servicesandprice',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='servicesandprice',
            name='service',
            field=models.TextField(max_length=100, verbose_name='Послуга'),
        ),
        migrations.AlterField(
            model_name='servicesandprice',
            name='si',
            field=models.CharField(blank=True, default='грн', max_length=20, null=True, verbose_name='Одиниці виміру'),
        ),
    ]
